Hospital-Management-System.App.WebMvcUI/Controllers/AdminController.cs
using Hospital_Management_System.App.WebMvcUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Hospital_Management_System.App.WebMvcUI.Controllers
{
    [Authorize(Roles = "admin")]
    public class AdminController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Hospital-Management-System.App.WebMvcUI/Controllers/DoctorController.cs
using Hospital_Management_System.DataAccess.Repositories;
using Hospital_Management_System.Entity.Entities;
using Hospital_Management_System.Entity.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Hospital_Management_System.App.WebMvcUI.Controllers
{
    [Authorize(Roles = "admin,hospital,doctor")]
    public class DoctorController : Controller
    {
        private readonly DoctorRepository _doctorRepo;
        private readonly AppointmentRepository _appointmentRepo;
        private readonly PrescriptionRepository _prescriptionRepo;

        public DoctorController(DoctorRepository doctorRepo, AppointmentRepository appointmentRepo, PrescriptionRepository prescriptionRepo)
        {
            _doctorRepo = doctorRepo;
            _appointmentRepo = appointmentRepo;
            _prescriptionRepo = prescriptionRepo;
        }

        public IActionResult List(string? search)
        {
            var doctors = _doctorRepo.GetAll();
            if (search != null)
            {
                doctors = doctors.Where(p => p.Name.ToLower().Contains(search.ToLower().Trim())).ToList();
            }
            return View(doctors);
        }
        [Authorize(Roles = "admin")]
        public IActionResult Index(int? id)
        {
            var doctors = _doctorRepo.GetAll();
            return View(doctors);
        }

        public IActionResult Details(int id)
        {
            var doctor = _doctorRepo.GetById(id);
            if (doctor == null)
            {
                return NotFound();
            }

            var appointments = _appointmentRepo.GetByDoctorId(id);
            var prescriptions = _prescriptionRepo.GetByDoctorId(id);

            var viewModel = new DoctorDetailsViewModel
            {
                Doctors = doctor,
                Appointments = appointments,
                Prescriptions = prescriptions
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_doctorRepo.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Doctor model)
        {
            _doctorRepo.Add(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(_doctorRepo.GetAll(), "Id", "Name");
            var doctor = _doctorRepo.GetById(id);
            return View(doctor);
        }

        [HttpPost]
        public IActionResult Edit(Doctor model)
        {
            _doctorRepo.Update(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var doctor = _doctorRepo.GetById(id);
            _doctorRepo.Delete(doctor);
            return RedirectToAction("Index", "Home");
        }
    }
}

Hospital-Management-System.App.WebMvcUI/Controllers/HospitalController.cs
using Hospital_Management_System.DataAccess.Repositories;
using Hospital_Management_System.Entity.Entities;
using Hospital_Management_System.Entity.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace Hospital_Management_System.App.WebMvcUI.Controllers
{
    [Authorize(Roles = "hospital,admin")]
    public class HospitalController : Controller
    {
        private readonly HospitalRepository _hospitalRepo;
        private readonly DoctorRepository _doctorRepo;
        private readonly AppointmentRepository _appointmentRepo;

        public HospitalController(HospitalRepository hospitalRepo, DoctorRepository doctorRepo, AppointmentRepository appointmentRepo)
        {
            _hospitalRepo = hospitalRepo;
            _doctorRepo = doctorRepo;
            _appointmentRepo = appointmentRepo;
        }

        public IActionResult List(string? search)
        {
            var hospitals = _hospitalRepo.GetAll();
            if (search != null)
            {
                hospitals = hospitals.Where(p => p.Name.ToLower().Contains(search.ToLower().Trim())).ToList();
            }
            return View(hospitals);
        }

        [Authorize(Roles = "admin")]
        public IActionResult Index(int? id)
        {
            var hospitals = _hospitalRepo.GetAll();
            return View(hospitals);
        }

        public IActionResult Details(int id)
        {
            var hospital = _hospitalRepo.GetById(id);
            if (hospital == null)
            {
                return NotFound();
            }

            var doctors = _doctorRepo.GetAll().Where(d => d.HospitalId == id).ToList();
            var appointments = _appointmentRepo.GetByHospitalId(id).ToList();

            var viewModel = new HospitalDetailsViewModel
            {
                Hospital = hospital,
                Doctors = doctors,
                Appointments = appointments
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_hospitalRepo.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Hospital model)
        {
            _hospitalRepo.Add(model);  // Formdan gelen Hospital modelini veritabanına ekler.
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(_hospitalRepo.GetAll(), "Id", "Name");
            var hospital = _hospitalRepo.GetById(id);
            return View(hospital);
        }

        [HttpPost]
        public IActionResult Edit(Hospital model)
        {
            _hospitalRepo.Update(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var hospital = _hospitalRepo.GetById(id);
            _hospitalRepo.Delete(hospital);
            return RedirectToAction("Index", "Home");
        }
    }
}

Hospital-Management-System.App.WebMvcUI/Controllers/PatientController.cs
using Hospital_Management_System.DataAccess.Repositories;
using Hospital_Management_System.Entity.Entities;
using Hospital_Management_System.Entity.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace Hospital_Management_System.App.WebMvcUI.Controllers
{
    [Authorize(Roles = "admin,hospital,doctor,patient")]
    public class PatientController : Controller
    {
        private readonly PatientRepository _patientRepo;

        public PatientController(PatientRepository patientRepo)
        {
            _patientRepo = patientRepo;
        }

        public IActionResult List(string? search)
        {
            var patients = _patientRepo.GetAll();
            if (search != null)
            {
                patients = patients.Where(p => p.Name.ToLower().Contains(search.ToLower().Trim())).ToList();
            }
            return View(patients);
        }
        [Authorize(Roles = "admin")]
        public IActionResult Index(int? id)
        {
            var patients = _patientRepo.GetAll();
            return View(patients);
        }

        public IActionResult Details(int id)
        {
            var patient = _patientRepo.GetById(id);
            if (patient == null)
            {
                return NotFound();
            }
            var appointments = _patientRepo.GetAppointmentsByPatientId(id);
            var prescriptions = _patientRepo.GetPrescriptionsByPatientId(id);

            var viewModel = new PatientDetailsViewModel
            {
                Patients = patient,
                Appointments = appointments,
                Prescriptions = prescriptions
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Categories = new SelectList(_patientRepo.GetAll(), "Id", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Create(Patient model)
        {
            _patientRepo.Add(model);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Categories = new SelectList(_patientRepo.GetAll(), "Id", "Name");
            var patient = _patientRepo.GetById(id);
            return View(patient);
        }

        [HttpPost]
        public IActionResult Edit(Patient model)
        {
            _patientRepo.Update(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var patient = _patientRepo.GetById(id);
            _patientRepo.Delete(patient);
            return RedirectToAction("Index", "Home");
        }
    }
}

Hospital-Management-System.App.WebMvcUI/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin Panel";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #e9ecef;
            color: #333;
            transition: opacity 0.5s ease;
        }

        .fade-out {
            opacity: 0;
        }

        .admin-panel-container {
            margin: 50px auto;
            width: 300px;
            text-align: center;
        }

            .admin-panel-container h2 {
                margin-bottom: 30px;
            }

            .admin-panel-container .btn {
                display: block;
                width: 100%;
                margin-bottom: 10px;
                border-radius: 10px;
                transition: background-color 0.3s, color 0.3s;
            }

            .admin-panel-container .btn-primary:hover {
                background-color: #0056b3;
                color: white;
            }

            .admin-panel-container .btn-success:hover {
                background-color: #218838;
                color: white;
            }

            .admin-panel-container .btn-info:hover {
                background-color: #138496;
                color: white;
            }

            .admin-panel-container .btn-secondary:hover {
                background-color: #5a6268;
                color: white;
            }

            .admin-panel-container .btn-dark:hover {
                background-color: #1d2124;
                color: white;
            }
    </style>
</head>
<body>
    <div class="admin-panel-container">
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <h2>Admin Panel</h2>

        <a asp-controller="Hospital" asp-action="Index" class="btn btn-primary">Hospital Index</a>
        <a asp-controller="Doctor" asp-action="Index" class="btn btn-success">Doctor Index</a>
        <a asp-controller="Patient" asp-action="Index" class="btn btn-info">Patient Index</a>
        <a asp-controller="Prescription" asp-action="Index" class="btn btn-secondary">Prescription Index</a>
        <a asp-controller="Appointment" asp-action="Index" class="btn btn-dark">Appointment Index</a>
    </div>
    <!-- footer -->
    <footer>
        <div class="w3ls-footer-grids pt-sm-4 pt-3">
            <div class="container py-xl-5 py-lg-3">
                <div class="row">
                    <div class="col-md-4 w3l-footer">
                        <h2 class="mb-sm-3 mb-2">
                            <a href="index.html" class="text-white font-italic font-weight-bold">
                                <span>Wiss</span>Hoss
                                <i class="fas fa-syringe ml-2"></i>
                            </a>
                        </h2>
                        <p>
                            Our hospital's contact details are provided on the side. Please do not hesitate to reach out if you have any questions. We are here to offer you the best service with our expert team.
                        </p>
                    </div>
                    <div class="col-md-4 w3l-footer my-md-0 my-4">
                        <h3 class="mb-sm-3 mb-2 text-white">Address</h3>
                        <ul class="list-unstyled">
                            <li>
                                <i class="fas fa-location-arrow float-left"></i>
                                <p class="ml-4">
                                    Barbaros Bulvarı Yıldız İş Hanı
                                    <span>Beşiktaş / İstanbul.</span>
                                </p>
                                <div class="clearfix"></div>
                            </li>
                            <li class="my-3">
                                <i class="fas fa-phone float-left"></i>
                                <p class="ml-4">1234567890</p>
                                <div class="clearfix"></div>
                            </li>
                            <li>
                                <i class="far fa-envelope-open float-left"></i>
                                <a href="mailto:info@example.com" class="ml-3">mail@example.com</a>
                                <div class="clearfix"></div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4 w3l-footer">
                        <h3 class="mb-sm-3 mb-2 text-white">Quick Links</h3>
                        <div class="nav-w3-l">
                            <ul class="list-unstyled">
                                <li>
                                    <a href="/Home/index">Home</a>
                                </li>
                                <li class="mt-2">
                                    <a href="/Home/About">About Us</a>
                                </li>
                                <li class="mt-2">
                                    <a href="/Home/Gallery">Gallery</a>
                                </li>
                                <li class="mt-2">
                                    <a href="/AppointmentRequest/Appointment">Appointment</a>
                                </li>

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="border-top mt-5 pt-lg-4 pt-3 pb-lg-0 pb-3 text-center">
                    <p class="copy-right-grids mt-lg-1">
                        &copy; 2024 WissHoss. All Rights Reserved | Design by WissHoss
                    </p>
                </div>
            </div>
        </div>
    </footer>
    <!-- //footer -->

    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            const links = document.querySelectorAll('a.btn');
            links.forEach(link => {
                link.addEventListener('click', (e) => {
                    e.preventDefault();
                    document.body.classList.add('fade-out');
                    setTimeout(() => {
                        window.location.href = link.href;
                    }, 500);
                });
            });
        });
    </script>
</body>
</html>

Hospital-Management-System.App.WebMvcUI/Views/Admin/List.cshtml
@using Hospital_Management_System.Entity.Entities
@model List<Hospital>
@{
    ViewData["Title"] = "List";


}

<h3>Ürünler</h3>

<div class="row">
    @foreach (var p in Model)
    {
        <div class="col-md-4">
            <div class="card mb-3">
                <div class="card-header text-center">
                    <h5 class="card-title">@p.Name</h5>
                </div>
                <div class="card-body text-center">
                    <p class="card-text">Fiyat : @string.Format("{0:C2}", p.PhoneNumber)</p>
                    <a asp-controller="Admin" asp-action="Details" asp-route-id="@p.Id" class="btn btn-primary">Details</a>
@*                     <a href="/Product/Details/@p.Id"class="btn btn-primary">Details</a> *@
                </div>
            </div>
        </div>
    }
</div>